services:
  web:
    image: websockets-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBAPIKEY

  # Minio is used where there is no S3 available, as it provides an S3 compatible service.
  # For example, when running on AWS or CREODIAS an S3 service is available,
  # and therefore Minio is not required, but it is required when running on a local machine.
  # Therefore, when running on AWS or CREODIAS, Minio could be deactivated, as it is redundant.
  minio:
    image: minio/minio
    restart: always
    network_mode: host
    volumes:
      - eo-vol:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 300s
      timeout: 20s
      retries: 3
volumes:
    eo-vol: