services:
  web:
    image: websockets-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBAPIKEY
  minio:
    image: minio/minio
    restart: always
    network_mode: host
    volumes:
      - eo-vol:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 300s
      timeout: 20s
      retries: 3
volumes:
    eo-vol: